<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use App\Scopes\ClusterScope;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Builder;

class CloseNumber extends Model
{
    use SoftDeletes;
    use HasFactory;
    use Searchable;

    protected $fillable = ['combination', 'game_id', 'draw_period_id'];

    protected $searchableFields = ['*'];

    public static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('currentDraw', function (Builder $builder){
            $builder->whereDate('created_at', Carbon::today())
                ->whereHas('drawPeriod', function ($query) {
                    $query
                        ->whereTime('open_time', '<', Carbon::now()->toTimeString())
                        ->whereTime('close_time', '>', Carbon::now()->toTimeString());
                });
        });
    }

    public function game()
    {
        return $this->belongsTo(Game::class);
    }

    public function drawPeriod()
    {
        return $this->belongsTo(DrawPeriod::class);
    }

}
