<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use App\Scopes\ClusterScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Matrix\Builder;

class Winner extends Model
{
    use SoftDeletes;
    use HasFactory;
    use Searchable;

    protected $fillable = ['bet_id', 'draw_result_id'];

    protected $searchableFields = ['*'];

    public static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
//        static::addGlobalScope('clusterWinnerScope', function (Builder $builder){
//            $builder->
//        });
    }


    public function bet()
    {
        return $this->belongsTo(Bet::class);
    }

    public function drawResult()
    {
        return $this->belongsTo(DrawResult::class);
    }
}
